proxylist/fixtures/proxies.json, proxylist/tests.py, proxylist/views.py
- Only return ports for active proxies
=> Show ports for online proxies

proxylist/tests.py
to be consistent with the purpose of the test
=> Rename ports tests

proxylist/serializers.py
so it shows when querying the API
=> Add port to the proxy serializer

proxylist/tests.py, proxylist/views.py, shadowmere/urls.py
this way it can be added to the router and it's shown in the automatic documentation
=> Move the country code endpoint to a ViewSet

proxylist/tests.py, proxylist/views.py, shadowmere/urls.py
this way it can be added to the router and it's shown in the automatic documentation
=> Move the ports endpoint to a ViewSet

proxylist/tests.py
=> Add tests to check that the QR generation works

proxylist/tests.py, proxylist/views.py, shadowmere/urls.py
tobe able to use it with directly with the shadowsocks app
=> Add subscription endpoint

proxylist/tests.py
contributes towards https://github.com/jadolg/shadowmere/issues/40
=> Add test to check that listing proxies work as intended

proxylist/base64_decoder.py, proxylist/models.py, proxylist/tests/test_proxies.py
=> Move base64 exception checking one level below

proxylist/tests/test_proxies.py
- Add test to verify that the same proxy can't be added twice
- Add a second case to verify that needs to be translated into SIP002 first
=> Add tests to validate that duplicates can't be inserted

proxylist/tests/test_subscription.py, proxylist/views.py, requirements.txt
This should solve https://github.com/jadolg/shadowmere/issues/98
=> Add emoji flags to subscriptions

proxylist/tasks.py
base64 subscriptions are lists of base64 encoded lists of proxies.
=> Add support for base64 subscriptions

.env.shadowtest.example, docker-compose.yml, shadowmere/settings.py
=> Remove shadowtest deployment

proxylist/tasks.py
his way the checks continue after a connection error
=> Capture ConnectionError when polling subscriptions

proxylist/tasks.py
=> Capture SSL error

proxylist/tasks.py
polling one subscription is constantly failing because of this and there's no clear way to fix it.
=> Extract decoding lines into a separate function and handle UnicodeDecodeError there

proxylist/tasks.py
=> Do not fail when status code is != 200

proxylist/tasks.py
it was not working for PLAIN subscriptions
=> Fix indentation in alive_timestamp

proxylist/tasks.py
to cleanly skip tests if the nework isn't reachable
=> Check for common errors when prompting Google's 204 generator

proxylist/metrics.py, proxylist/views.py
Adds metrics totaling the currently indexed proxies and the total active proxies from the list
=> Add custom proxy metrics

docker-compose.yml, proxylist/fixtures/proxies.json, proxylist/management/commands/poll_subscriptions.py, proxylist/management/commands/remove_low_quality.py, proxylist/scheduled_tasks.py, proxylist/tasks.py, proxylist/tests/test_tasks.py, proxylist/views.py
This way we don't need to manually remove old dead proxies.
=> Periodically remove inactive proxies with less than 20% success rate

proxylist/views.py, requirements.txt, shadowmere/settings.py
to discourage scrapers from abusing the service
=> Add ratelimiting

proxylist/management/commands/initadmin.py, proxylist/tasks.py, requirements.txt, shadowmere/settings.py
This makes it better to parse in the server
=> Switch logs to use a json formatter

.github/workflows/docker-image.yml, .github/workflows/docker-pr.yml
in order to be able to run docker builds on PRs
=> Separate docker build actions

README.md, proxylist/metrics.py, proxylist/models.py, proxylist/proxy.py, proxylist/tasks.py
This is a sample of one of our most popular and useful codemods, it automagically adds the `-> None` type annotation to all functions that have no return statement or that return none.
<details><summary>
✨ Click to expand
</summary>
- ❓ <b>What if this PR has errors?</b>
- If this PR was created from a GPT chat, you can post the error in the chat and the agent will try to resolve it for you 🙏. Or you can post the error in <a href="https://thecodegen.slack.com/archives/C07EKNJE8P5">our slack channel</a> 🤝!
- ❓ <b>Should I merge this PR or does Codegen?</b>
- Codegen does not merge PRs. It's up to you to review the changes and merge the PR when you're ready 🎉. This allows internal engineers to control when/if the changes merge into master 🙇.
- ❓ <b>What if I want to talk to a human about …
=> [Codegen] 🔧 Add None Return Type Annotations (Excluding Main)

README.md, proxylist/models.py, proxylist/tasks.py, proxylist/views.py
This is a sample of one of our most popular and useful codemods, it automagically converts unnamed args to named args 🎉.
<details><summary>
✨ Click to expand
</summary>
- ❓ <b>What if this PR has errors?</b>
- If this PR was created from a GPT chat, you can post the error in the chat and the agent will try to resolve it for you 🙏. Or you can post the error in <a href="https://thecodegen.slack.com/archives/C07EKNJE8P5">our slack channel</a> 🤝!
- ❓ <b>Should I merge this PR or does Codegen?</b>
- Codegen does not merge PRs. It's up to you to review the changes and merge the PR when you're ready 🎉. This allows internal engineers to control when/if the changes merge into master 🙇.
- ❓ <b>What if I want to talk to a human about this PR?</b>
- Message in <a …
=> [Codegen] 🔧 Convert Function Calls to Use Named Keyword Arguments

proxylist/proxy.py
- **Use proxy url sha256 hash as cache key instead of plain proxy url**
=> Use proxy url sha256 hash as cache key instead of plain proxy url
